[package]
name = "toolshub"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-http = { version = "0.4.1", features = ["fs"] }
axum = "0.6"
tokio = { version = "1", features = ["full"] }
askama = "0.12"

