[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }

# Migration library with runtime and PostgreSQL support
sea-orm-migration = { version = "1.1", features = ["runtime-tokio-native-tls", "sqlx-postgres"] }

# ORM library for interacting with the database
sea-orm = "0.11"

# SQLx with PostgreSQL support
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres"] }

# Tokio for async runtime
tokio = { version = "1", features = ["full"] }